//
//  GameHUD.swift
//  C64-Returnal
//

import SpriteKit

final class GameHUD {
    let topStatusBackground = SKShapeNode()
    let combatStatusBackground = SKShapeNode()
    let levelUpBackground = SKShapeNode()
    let chestRewardBackground = SKShapeNode()
    let gameOverBackground = SKShapeNode()
    let gameOverLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let restartLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let exitLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let levelUpLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let chestRewardLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let chestRewardContinueLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let fireRateLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let extraFireballLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let extraLifeLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let halveSkeletonsLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let learnLightningLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let lightningBounceLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let lightningRateLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let learnOrbLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let extraOrbLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let orbitalSpeedLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let learnBeamLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let beamRateLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let beamKillCountLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let learnMeteorLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let extraMeteorLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let meteorRateLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let firstLevelUpKeyLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let secondLevelUpKeyLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let thirdLevelUpKeyLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let fourthLevelUpKeyLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let fireRateIcon = SKSpriteNode()
    let extraFireballIcon = SKSpriteNode()
    let extraLifeIcon = SKSpriteNode()
    let halveSkeletonsIcon = SKSpriteNode()
    let learnLightningIcon = SKSpriteNode()
    let lightningBounceIcon = SKSpriteNode()
    let lightningRateIcon = SKSpriteNode()
    let learnOrbIcon = SKSpriteNode()
    let extraOrbIcon = SKSpriteNode()
    let orbitalSpeedIcon = SKSpriteNode()
    let learnBeamIcon = SKSpriteNode()
    let beamRateIcon = SKSpriteNode()
    let beamKillCountIcon = SKSpriteNode()
    let learnMeteorIcon = SKSpriteNode()
    let extraMeteorIcon = SKSpriteNode()
    let meteorRateIcon = SKSpriteNode()
    let levelLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let experienceLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let fireballIcon = SKSpriteNode()
    let fireballCountLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let fireballIntervalLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let fireballKillsLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let lightningIcon = SKSpriteNode()
    let lightningCountLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let lightningIntervalLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let lightningKillsLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let orbIcon = SKSpriteNode()
    let orbCountLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let orbSpeedLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let orbKillsLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let beamIcon = SKSpriteNode()
    let beamKillLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let beamIntervalLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let beamKillsLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let meteorIcon = SKSpriteNode()
    let meteorCountLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let meteorIntervalLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let meteorKillsLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let skeletonIcon = SKSpriteNode()
    let skeletonAliveLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    let skeletonIntervalLabel = SKLabelNode(fontNamed: "Menlo-Bold")
    var activeLevelUpOptions = [LevelUpOption]()
    var activeChestRewardItems = [ChestRewardDisplayItem]()
    var chestRewardNodes = [SKNode]()
    var lifeIcons = [SKSpriteNode]()
    var lifeTexture: SKTexture?
    var lifeIconOrigin = CGPoint.zero
    var currentLives = 0
    var currentSceneSize = CGSize(width: 800, height: 600)
    weak var parentNode: SKNode?

    func add(to parent: SKNode, fireballTexture: SKTexture, lightningTexture: SKTexture, orbTexture: SKTexture, beamTexture: SKTexture, meteorTexture: SKTexture, lifeTexture: SKTexture, skeletonTexture: SKTexture) {
        parentNode = parent
        self.lifeTexture = lifeTexture

        setupGameOverLabel()
        setupLevelUpLabels(fireballTexture: fireballTexture, lightningTexture: lightningTexture, orbTexture: orbTexture, beamTexture: beamTexture, meteorTexture: meteorTexture, lifeTexture: lifeTexture, skeletonTexture: skeletonTexture)
        setupChestRewardLabels()
        setupProgressLabels()
        setupBackgroundPanels()
        setupFireballStatus(fireballTexture: fireballTexture)
        setupLightningStatus(lightningTexture: lightningTexture)
        setupOrbStatus(orbTexture: orbTexture)
        setupBeamStatus(beamTexture: beamTexture)
        setupMeteorStatus(meteorTexture: meteorTexture)
        setupSkeletonStatus(skeletonTexture: skeletonTexture)

        parent.addChild(topStatusBackground)
        parent.addChild(combatStatusBackground)
        parent.addChild(levelUpBackground)
        parent.addChild(chestRewardBackground)
        parent.addChild(gameOverBackground)
        parent.addChild(gameOverLabel)
        parent.addChild(restartLabel)
        parent.addChild(exitLabel)
        parent.addChild(levelUpLabel)
        parent.addChild(chestRewardLabel)
        parent.addChild(chestRewardContinueLabel)
        parent.addChild(fireRateLabel)
        parent.addChild(extraFireballLabel)
        parent.addChild(extraLifeLabel)
        parent.addChild(halveSkeletonsLabel)
        parent.addChild(learnLightningLabel)
        parent.addChild(lightningBounceLabel)
        parent.addChild(lightningRateLabel)
        parent.addChild(learnOrbLabel)
        parent.addChild(extraOrbLabel)
        parent.addChild(orbitalSpeedLabel)
        parent.addChild(learnBeamLabel)
        parent.addChild(beamRateLabel)
        parent.addChild(beamKillCountLabel)
        parent.addChild(learnMeteorLabel)
        parent.addChild(extraMeteorLabel)
        parent.addChild(meteorRateLabel)
        parent.addChild(firstLevelUpKeyLabel)
        parent.addChild(secondLevelUpKeyLabel)
        parent.addChild(thirdLevelUpKeyLabel)
        parent.addChild(fourthLevelUpKeyLabel)
        parent.addChild(fireRateIcon)
        parent.addChild(extraFireballIcon)
        parent.addChild(extraLifeIcon)
        parent.addChild(halveSkeletonsIcon)
        parent.addChild(learnLightningIcon)
        parent.addChild(lightningBounceIcon)
        parent.addChild(lightningRateIcon)
        parent.addChild(learnOrbIcon)
        parent.addChild(extraOrbIcon)
        parent.addChild(orbitalSpeedIcon)
        parent.addChild(learnBeamIcon)
        parent.addChild(beamRateIcon)
        parent.addChild(beamKillCountIcon)
        parent.addChild(learnMeteorIcon)
        parent.addChild(extraMeteorIcon)
        parent.addChild(meteorRateIcon)
        parent.addChild(levelLabel)
        parent.addChild(experienceLabel)
        parent.addChild(fireballIcon)
        parent.addChild(fireballCountLabel)
        parent.addChild(fireballIntervalLabel)
        parent.addChild(fireballKillsLabel)
        parent.addChild(lightningIcon)
        parent.addChild(lightningCountLabel)
        parent.addChild(lightningIntervalLabel)
        parent.addChild(lightningKillsLabel)
        parent.addChild(orbIcon)
        parent.addChild(orbCountLabel)
        parent.addChild(orbSpeedLabel)
        parent.addChild(orbKillsLabel)
        parent.addChild(beamIcon)
        parent.addChild(beamKillLabel)
        parent.addChild(beamIntervalLabel)
        parent.addChild(beamKillsLabel)
        parent.addChild(meteorIcon)
        parent.addChild(meteorCountLabel)
        parent.addChild(meteorIntervalLabel)
        parent.addChild(meteorKillsLabel)
        parent.addChild(skeletonIcon)
        parent.addChild(skeletonAliveLabel)
        parent.addChild(skeletonIntervalLabel)
    }


    static let primaryTextColor = SKColor(calibratedRed: 0.96, green: 0.93, blue: 0.83, alpha: 1)
    static let keyHintTextColor = SKColor(calibratedRed: 1.0, green: 0.86, blue: 0.26, alpha: 1)
    static let deathTextColor = SKColor(calibratedRed: 0.95, green: 0.05, blue: 0.08, alpha: 1)
    static let panelColor = SKColor(calibratedWhite: 0.02, alpha: 1)
    static let panelAlpha: CGFloat = 0.62
    static let panelCornerRadius: CGFloat = 6
    static let lifeIconSize: CGFloat = 14
    static let lifeIconsPerRow = 12
    static let lifeIconSpacing: CGFloat = 16
}
